### ISSUE TITLE
set size for each word

### ISSUE THREAD

**Issue by hisham2007** [alhazmy13/AndroidWordCloud#2]
شكرا على العمل المميز. اواجه مشكله انني اريد ان اغير حجم كل كلمه حتى اعطي قوه لبعض الكلمات مثلا كلمات يكثر البحث عنها عن الكلمات الاخرى

**Comment by alhazmy13** [comment]
اهلا,, 
تقدر تميز الكلمات عن غيرها وذلك بتحديد `weight` لكل كلمة من خلال الكلاس `WordCloud` كل مازاد الحجم للكلمة كل مازاد الخط واصبحت مميزة 
 ```java
 public WordCloud(String text, int weight) {
        this.text = text;
        this.weight = weight;
    }```
