### ISSUE TITLE
how to fit words in different shapes and to show all words.

### ISSUE THREAD

**Issue by nicks258** [alhazmy13/AndroidWordCloud#4]
Thanks for such a wonderful work! can you tell me how to fit words in different shapes.and also currently it does not show all words it takes a random words every time. Like this->
![device-2017-06-16-182227](https://user-images.githubusercontent.com/11635407/27227358-ccbe675c-52c0-11e7-9b02-7f183a3d57bf.png)

**Comment by alhazmy13** [comment]
Hi @nicks258 ,
This library depends to `d3-cloud` and in actuality there's no way to create a different shape with `d3` .
Maybe I'll try to support another js library

Thanks,,
