### ISSUE TITLE
Any plans for clickevent on each word?

### ISSUE THREAD

**Issue by AndroidOutThere** [alhazmy13/AndroidWordCloud#5]
Hi,

Do you have any plan to update library so that it has click listener for each word ?

Thanks.

**Comment by alhazmy13** [comment]
Hi @hashmat123 
Maybe with next versions.
Thanks

**Comment by AndroidOutThere** [comment]
I did implement click events.
But I see the words are displayed with some time lag. Is it possible to
enhance the time to display?

Thanks.
